spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc?serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
